import numpy as np
import matplotlib.pyplot as plt
import os
import math

# --- EVALUATION CONFIGURATION ---
# Define the penetration levels to evaluate. Modify these to change the scenario outputs.
SCENARIOS = [150, 200, 250]
SCENARIO_LABELS = ['150 EVs (Low Stress)', '200 EVs (Medium Stress)', '250 EVs (High Stress)']

# --- GRAPHICS SETTINGS ---

plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Times New Roman', 'DejaVu Serif']
plt.rcParams['font.size'] = 10
plt.rcParams['axes.titlesize'] = 11
plt.rcParams['axes.labelsize'] = 10


def load_simulation_data(scenarios):
    """
    Ingests the raw .npz array files generated by the simulation engine.
    Dynamically loads based on the configured scenarios list.
    """
    data = {}

    print("--- INGESTING SIMULATION MATRICES ---")
    for ev in scenarios:
        filename = f"SimulationData_{ev}EVs_1000.npz"
        if not os.path.exists(filename):
            raise FileNotFoundError(f"CRITICAL: Missing data file '{filename}'. Execute the engine for {ev} EVs first.")

        data[ev] = np.load(filename)
        print(f"Loaded {ev} EV matrix successfully.")

    return data


def plot_grouped_box_whisker(data, scenarios, labels):
    """
    Generates Figure 5.1: Grouped single-axis Box-and-Whisker plot.
    Dynamically scales spatial clustering based on the number of provided scenarios.
    Title removed for IEEE caption compliance.
    """
    print("\nGenerating Figure 5.1: Grouped Box-and-Whisker Plot...")

    fig, ax = plt.subplots(figsize=(10, 6), dpi=300)

    # Dynamically extract structural voltage data via list comprehension
    disorderly_data = [data[ev]['d_min_volts'] for ev in scenarios]
    orderly_data = [data[ev]['o_min_volts'] for ev in scenarios]

    # Dynamically define horizontal X-axis clustering positions
    num_scenarios = len(scenarios)
    positions_d = [i * 3 + 1 for i in range(num_scenarios)]
    positions_o = [i * 3 + 2 for i in range(num_scenarios)]
    tick_positions = [i * 3 + 1.5 for i in range(num_scenarios)]

    # Render Disorderly Baseline (Red)
    bp_d = ax.boxplot(disorderly_data, positions=positions_d, patch_artist=True, widths=0.75,
                      boxprops=dict(facecolor='crimson', color='black', alpha=0.8),
                      medianprops=dict(color='white', linewidth=1),
                      flierprops=dict(marker='o', markerfacecolor='crimson', markeredgecolor='black', markersize=4,
                                      alpha=0.5))

    # Render Orderly MTOUCP (Blue)
    bp_o = ax.boxplot(orderly_data, positions=positions_o, patch_artist=True, widths=0.75,
                      boxprops=dict(facecolor='royalblue', color='black', alpha=0.8),
                      medianprops=dict(color='white', linewidth=1),
                      flierprops=dict(marker='o', markerfacecolor='royalblue', markeredgecolor='black', markersize=4,
                                      alpha=0.5))

    # Enforce Statutory Minimum Threshold
    stat_line = ax.axhline(y=0.95, color='black', linestyle='--', linewidth=1.5, label='Statutory Limit (0.95 p.u.)')

    # Figure Formatting
    ax.set_ylabel("Absolute Minimum Voltage (p.u.)")

    # Centre the categorical labels between the dynamic grouped boxes
    ax.set_xticks(tick_positions)
    ax.set_xticklabels(labels)

    # Construct precise engineering legend
    ax.legend([bp_d["boxes"][0], bp_o["boxes"][0], stat_line],
              ['Disorderly (Baseline)', 'Orderly ', 'IEC Statutory Limit (0.95 p.u.)'],
              loc='lower left', framealpha=0.9, edgecolor='black')

    # Y-axis bounds configuration
    highest_stress_ev = scenarios[-1]
    y_min_val = min(np.min(data[highest_stress_ev]['d_min_volts']),
                    np.min(data[highest_stress_ev]['o_min_volts'])) - 0.005

    top_limit = 0.97
    ax.set_ylim(bottom=y_min_val, top=top_limit)

    # Force highly granular ticks (every 0.005 p.u.) to stretch out the visual space
    tick_min = math.floor(y_min_val * 200) / 200.0
    ax.set_yticks(np.arange(tick_min, top_limit + 0.001, 0.005))

    ax.grid(True, axis='y', linestyle=':', alpha=0.7)

    plt.tight_layout()
    filename = "Figure_5_1_Voltage_Distribution.png"
    plt.savefig(filename, format='png', bbox_inches='tight')
    print(f"Plot extraction successful. Saved as: {filename}")
    plt.close()


def plot_temporal_losses(data, scenarios, labels):
    """
    Generates Figure 5.2: 48-Hour Temporal Loss Profiles.
    Uses a 3x1 vertically stacked layout to expose quadratic loss penalties.
    Title removed for IEEE caption compliance.
    """
    print("\nGenerating Figure 5.2: 48-Hour Temporal Loss Profiles...")

    num_scenarios = len(scenarios)
    time_axis = np.linspace(0, 48, 288)

    fig, axes = plt.subplots(num_scenarios, 1, figsize=(10, 3.5 * num_scenarios), dpi=300, sharex=True)

    if num_scenarios == 1:
        axes = [axes]

    for i, ev in enumerate(scenarios):
        ax = axes[i]

        # Extract mean active power loss matrices
        d_losses = data[ev]['d_mean_step_losses']
        o_losses = data[ev]['o_mean_step_losses']

        ax.plot(time_axis, d_losses, color='crimson', linewidth=1.5, label='Disorderly (Baseline)')
        ax.plot(time_axis, o_losses, color='royalblue', linewidth=1.5, label='Orderly ')

        # Shade the off-peak tariff/charging windows to support valley-filling analysis
        ax.axvspan(0.0, 7.0, color='lightgray', alpha=0.3, label='Off-Peak Window' if i == 0 else "")
        ax.axvspan(24.0, 31.0, color='lightgray', alpha=0.3)
        ax.axvspan(48.0, 55.0, color='lightgray', alpha=0.3)

        ax.set_ylabel(f"{labels[i]}\nActive Power Losses (kW)")
        ax.grid(True, linestyle=':', alpha=0.7)

        # Determine dynamic Y-axis maximum for the current subplot
        max_y = max(np.max(d_losses), np.max(o_losses))
        ax.set_ylim(bottom=0, top=max_y * 1.1)

        if i == 0:
            ax.legend(loc='upper right', framealpha=0.9, edgecolor='black')

    # Apply categorical X-labels only to the bottom plot
    axes[-1].set_xlabel("Time (Hours)")
    axes[-1].set_xticks(np.arange(0, 49, 4))

    plt.tight_layout()
    filename = "Figure_5_2_Temporal_Losses.png"
    plt.savefig(filename, format='png', bbox_inches='tight')
    print(f"Plot extraction successful. Saved as: {filename}")
    plt.close()


def plot_spatial_tap_operations(data, scenarios, labels):
    """
    Generates Figure 5.3: Spatial Breakdown of Tap Operations.
    Uses a 3x1 vertically stacked layout to prevent bar clustering.
    Title removed for IEEE caption compliance.
    """
    print("\nGenerating Figure 5.3: Spatial Breakdown of Tap Operations...")

    REGULATORS = ['creg1a', 'creg1b', 'creg1c', 'creg2a', 'creg2b', 'creg2c']
    num_scenarios = len(scenarios)

    fig, axes = plt.subplots(num_scenarios, 1, figsize=(10, 3.5 * num_scenarios), dpi=300, sharex=True)

    if num_scenarios == 1:
        axes = [axes]

    x = np.arange(len(REGULATORS))
    width = 0.35

    for i, ev in enumerate(scenarios):
        ax = axes[i]

        # Extract mean operation matrices
        d_means = data[ev]['d_mean_tap_ops']
        o_means = data[ev]['o_mean_tap_ops']

        ax.bar(x - width / 2, d_means, width, label='Disorderly (Baseline)', color='crimson', edgecolor='black')
        ax.bar(x + width / 2, o_means, width, label='Orderly ', color='royalblue', edgecolor='black')

        ax.set_ylabel(f"{labels[i]}\nTotal Operations")
        ax.grid(True, axis='y', linestyle=':', alpha=0.7)

        if i == 0:
            ax.legend(loc='upper right', framealpha=0.9, edgecolor='black')

    # Apply categorical X-labels only to the bottom plot
    axes[-1].set_xticks(x)
    axes[-1].set_xticklabels(REGULATORS)

    plt.tight_layout()
    filename = "Figure_5_3_Spatial_Tap_Operations.png"
    plt.savefig(filename, format='png', bbox_inches='tight')
    print(f"Plot extraction successful. Saved as: {filename}")
    plt.close()


def plot_temporal_taps(data, scenarios, labels):
    """
    Generates Figure 5.4: 3x2 Grid of Temporal Step-Plots for creg1a and creg2a.
    Rows map to penetration levels. Columns map to spatial location (upstream vs downstream).
    Overarching suptitle removed for IEEE caption compliance. Subplot column headers retained.
    """
    print("\nGenerating Figure 5.4: Temporal Tap Trajectory (creg1a vs creg2a)...")

    num_scenarios = len(scenarios)
    time_axis = np.linspace(0, 48, 288)

    # Create a 3x2 grid, sharing axes to eliminate redundant ink
    fig, axes = plt.subplots(num_scenarios, 2, figsize=(12, 3.5 * num_scenarios), dpi=300, sharex=True, sharey=True)

    for i, ev in enumerate(scenarios):
        # Extract specific scenario matrices
        d_creg1a = data[ev]['d_mean_creg1a']
        o_creg1a = data[ev]['o_mean_creg1a']
        d_creg2a = data[ev]['d_mean_creg2a']
        o_creg2a = data[ev]['o_mean_creg2a']

        ax_up = axes[i, 0]  # Upstream (creg1a)
        ax_down = axes[i, 1]  # Downstream (creg2a)

        # --- Plot Upstream (creg1a) ---
        ax_up.step(time_axis, d_creg1a, where='post', color='crimson', linewidth=1.5, label='Disorderly')
        ax_up.step(time_axis, o_creg1a, where='post', color='royalblue', linewidth=1.5, label='Orderly')
        ax_up.set_ylabel(f"{labels[i]}\nTap Position")
        ax_up.grid(True, linestyle=':', alpha=0.7)

        # --- Plot Downstream (creg2a) ---
        ax_down.step(time_axis, d_creg2a, where='post', color='crimson', linewidth=1.5)
        ax_down.step(time_axis, o_creg2a, where='post', color='royalblue', linewidth=1.5)
        ax_down.grid(True, linestyle=':', alpha=0.7)

        # Add legend and column headers only to the top panels
        if i == 0:
            ax_up.set_title("Upstream Substation (creg1a)", fontweight='bold')
            ax_down.set_title("Downstream Lateral (creg2a)", fontweight='bold')
            ax_up.legend(loc='upper right', framealpha=0.9, edgecolor='black')

    # Shared X and Y formatting applied only to the edges
    for ax in axes[-1, :]:
        ax.set_xlabel("Time (Hours)")
        ax.set_xticks(np.arange(0, 49, 6))

    for ax in axes[:, 0]:
        ax.set_yticks(np.arange(-16, 17, 8))

    plt.tight_layout()
    filename = "Figure_5_4_Temporal_Taps.png"
    plt.savefig(filename, format='png', bbox_inches='tight')
    print(f"Plot extraction successful. Saved as: {filename}")
    plt.close()


def plot_tradeoff_decoupling():
    """
    Generates Figure 5.5: Dual-axis plot demonstrating the decoupling of
    grid stress (Voltage PoF) and consumer outcome (Mean Deficit).
    Operates independently of the .npz extraction pipeline.
    """
    print("\nGenerating Figure 5.5: Decoupling of Grid Stress and Consumer Deficit...")

    # Hardcoded scalar values derived from the 1000-run stochastic extraction
    categories = np.arange(3)
    labels = ['150 EVs\n(Low Stress)', '200 EVs\n(Medium Stress)', '250 EVs\n(High Stress)']

    voltage_pof = [0.1, 5.0, 33.6]
    mean_deficit = [0.402, 0.404, 0.404]

    # Instantiate strictly formatted IEEE landscape figure
    fig, ax1 = plt.subplots(figsize=(12, 6), dpi=300)

    # --- Primary Axis (Left - Grid Stress) ---
    color_pof = '#DC143C'  # Crimson
    line1 = ax1.plot(categories, voltage_pof, color=color_pof, marker='o', linestyle='-',
                     linewidth=2.5, markersize=10, label='Voltage PoF (Grid Stress)')

    ax1.set_ylabel('Voltage PoF (%)', color=color_pof, fontsize=12, fontweight='bold')
    ax1.tick_params(axis='y', labelcolor=color_pof, labelsize=11)
    ax1.set_ylim(0, 40)
    ax1.grid(axis='y', linestyle=':', color='lightgrey', alpha=0.8)

    # Apply categorical X-axis labels
    ax1.set_xticks(categories)
    ax1.set_xticklabels(labels, fontsize=11, fontweight='bold')

    # --- Secondary Axis (Right - Consumer Cost) ---
    ax2 = ax1.twinx()
    color_def = '#1E50A0'  # Royal Blue
    line2 = ax2.plot(categories, mean_deficit, color=color_def, marker='s', linestyle='-',
                     linewidth=2.5, markersize=10, label='Mean Deficit (Consumer Cost)')

    ax2.set_ylabel('Mean Consumer Deficit (kWh)', color=color_def, fontsize=12, fontweight='bold')
    ax2.tick_params(axis='y', labelcolor=color_def, labelsize=11)
    ax2.set_ylim(0, 0.5)

    # --- Legend Aggregation ---
    lines = line1 + line2
    labels_leg = [l.get_label() for l in lines]
    ax1.legend(lines, labels_leg, loc='upper center', framealpha=0.9, edgecolor='black', fontsize=11)

    plt.tight_layout()
    filename = "Figure_5_5_Tradeoff_Decoupling.png"
    plt.savefig(filename, format='png', bbox_inches='tight')
    print(f"Plot extraction successful. Saved as: {filename}")
    plt.close()


if __name__ == "__main__":
    try:
        # 1. Execute standard .npz-dependent visualisations
        sim_data = load_simulation_data(SCENARIOS)
        plot_grouped_box_whisker(sim_data, SCENARIOS, SCENARIO_LABELS)
        plot_temporal_losses(sim_data, SCENARIOS, SCENARIO_LABELS)
        plot_spatial_tap_operations(sim_data, SCENARIOS, SCENARIO_LABELS)
        plot_temporal_taps(sim_data, SCENARIOS, SCENARIO_LABELS)

        # 2. Execute independent scalar decoupling visualisation
        plot_tradeoff_decoupling()

    except Exception as e:
        print(f"Execution Fault: {e}")
